wandb_version: 1

epochs:
  desc: null
  value: 10000
batch_size:
  desc: null
  value: 1000
validation_intervals:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
early_stop_patience:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699527425.930385
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 13
      - 15
      - 16
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
