wandb_version: 1

epochs:
  desc: null
  value: 10000
batch_size:
  desc: null
  value: 5000
validation_intervals:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
early_stop_patience:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699577115.15108
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 2
      - 13
      - 15
      - 16
      4: 3.11.5
      5: 0.16.0
      6: 4.32.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
